- hosts: localhost
  gather_facts: true
  vars:
    rbenv:
      env: system
      version: v1.1.2
      default_ruby: 2.6.5
      rubies:
        - version: 2.6.5
          env:
            RUBY_CONFIGURE_OPTS: "--enable-shared --with-jemalloc"
    rbenv_extra_depends:
      - libjemalloc1
      - libjemalloc-dev
  
  roles:
    - { role: 'ansible-rbenv-role', tags: 'init', rbenv_users: "{{ ansible_user_id }}", become: yes }
    - { role: 'ansible-role-nodejs', tags: 'init', become: yes }
