- hosts: localhost
  gather_facts: true

  roles:
    - { role: 'ansible-role-nodejs', tags: 'init', become: yes, nodejs_install_npm_user: "{{ ansible_user_id }}" }
    - { role: 'install_rbenv', tags: 'init', rbenv_user: "{{ ansible_user_id }}" }
