---
- name: install packages Ubuntu
  apt:
    name: "{{ apt_packages }}"
    state: present
  become: true
  when: ansible_facts['distribution'] == "Ubuntu"

- name: install packages for CentOS
  yum: 
    name: "{{ yum_packages }}"
    state: present 
  become: true
  when: ansible_facts['distribution'] == "CentOS"
  
- name: clone rbenv
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ ansible_env.HOME }}/.rbenv"
    accept_hostkey: yes
    force: yes
  with_items: "{{ rbenv_user }}"  
  become: yes
  become_user: "{{ item }}"  

- name: clone rbenv plugins
  git:
    repo: "{{ ruby_build_repo }}"
    dest: "{{ ansible_env.HOME }}/.rbenv/plugins/ruby-build"
    accept_hostkey: yes
    force: yes
  with_items: "{{ rbenv_user }}"
  become: yes
  become_user: "{{ item }}"

- name: Test bashrc for line
  shell: "grep '^export PATH=$HOME/.rbenv/bin:$PATH;' {{ ansible_env.HOME }}/.bashrc -c || true"
  register: test_grep

- name: Ensure rbenv is sourced from the .bashrc
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    block: |
      export PATH=$HOME/.rbenv/bin:$PATH
      export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"
      eval "$(rbenv init -)"
    insertafter: EOF
    create: yes
  when: test_grep.stdout == "0"  
  
- name: install ruby
  shell: |
    export PATH="${HOME}/.rbenv/bin:${PATH}" 
    eval "$(rbenv init -)" 
    export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH" 
    rbenv install --skip-existing {{ ruby_version }} && \
    rbenv global {{ ruby_version }} && \
    rbenv rehash
  args:
    executable: /bin/bash
  with_items: "{{ rbenv_user }}"
  become: yes
  become_user: "{{ item }}"

- name: install bundler
  shell: |
    export PATH="${HOME}/.rbenv/bin:${PATH}" 
    eval "$(rbenv init -)" 
    export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH" 
    gem install --no-document bundler 
  with_items: "{{ rbenv_user }}"
  become: yes
  become_user: "{{ item }}"

- name: install rails
  shell: |
    export PATH="${HOME}/.rbenv/bin:${PATH}" 
    eval "$(rbenv init -)" 
    export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH" 
    gem install --no-document rails -v {{ rails_version }} && \
    rbenv rehash
  with_items: "{{ rbenv_user }}"
  become: yes
  become_user: "{{ item }}"

- name: Install PostgreSQL Ubuntu
  apt: name={{ item }} state=present install_recommends=no
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  when: ansible_facts['distribution'] == "Ubuntu" 

- name: Install PostgreSQL CentOS
  yum: name={{ item }} state=present install_recommends=no
  with_items:
    - postgresql
    - postgresql-server
    - postgresql-contrib
    - postgresql-plpython
    - python-psycopg2
  when: ansible_facts['distribution'] == "CentOS"
    
- name: Ensuring postgresql is started and enabled
  service:
    name: postgresql
    state: started
    enabled: True    
